name: Two Connected Jobs Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build   # 👈 This connects the second job to the first
    steps:
      - name: Run tests
        run: echo "Running tests after build is complete!"
